### ISSUE TITLE
Better variable names

### ISSUE THREAD

**Issue by markparolisi** [jenigooley/calorie_count#4]
For example, the name `food` could also be reasonably used for your `calories` dict. So, maybe `food` should be more specific like `food_consumed` or `user_intake` or something to separate from food=>calorie definitions. 

Also, `total` what? The var on ln#15 needs to say what it's a total of.

**Comment by jeniwho** [comment]
i fixed those names. The calorie dict is just a place holder untill I figure out how to use an API to get data
