### ISSUE TITLE
Careful when starting an infinite loop

### ISSUE THREAD

**Issue by markparolisi** [jenigooley/calorie_count#5]
`while True:` can get you into trouble. Look at refactoring that block without using that while statement

**Comment by jeniwho** [comment]
what does refactoring mean?

**Comment by jeniwho** [comment]
can i use a different while statement? a for loop? do i need to use sort of loop even?

**Comment by dillonko** [comment]
I will explain when I see you tomorrow.  For now you have to continue
practicing your code.
