### ISSUE TITLE
Use if name == main

### ISSUE THREAD

**Issue by markparolisi** [jenigooley/calorie_count#7]
Instead of just calling the function at the bottom of the file, it's better to use the standard block of

```
if __name__ == "__main__":
  calorie_count()
``

**Comment by jeniwho** [comment]
what is this ? ive seen it before. why is it better?

**Comment by dillonko** [comment]
Hey Jeni,
That is something that you will learn over time.  It is part of how you
make you program executable.  I will give you the basics of it later. These
are all things I have talked with you about earlier yesterday.  Don't worry
about it for now.

Best,
Dillon
